### ISSUE TITLE
Add the remaining HTTP methods

### ISSUE THREAD

**Issue by dcsg** [toin0u/HttpAdapter#1]
First of all is great thanks @toin0u for moving to another lib the `HttpAdapters` created by @willdurand.

IMO these `HttpAdapters` are limited, since they only suppert `GET` method and for a library that I have I will need POST. Before start coding just want to do a bit of brainstorm about the best implementation across all  the adpaters to implement the remaining HTTP methods.

What do you guys think about this?

**Comment by toin0u** [comment]
I think it will be great to have `POST` method :)

**Comment by dcsg** [comment]
IMO I think if we are going to change the code it would be better to make something that can be reused for any HTTP method. I'm thinking in something like this:

``` php
public function getContent($url, $method, array $headers = array(), $content = '')
{
    // ...
    return $content;
}
```

/cc @willdurand @toin0u

**Comment by dcsg** [comment]
@willdurand @toin0u any thoughts?

**Comment by willdurand** [comment]
I think it's worth following the FIG discussion about the HTTP layer. IMO this lib should deal with Request/Response, just like Guzzle and Buzz do.

**Comment by toin0u** [comment]
Very good idea Wiliam. I didn't know about this discussion :-/

**Comment by dcsg** [comment]
Me either, the HTTP interface on the FIG discussion is the right way to handle this. Will closing the issue and wait until the HTTP interface is approved. Thanks for sharing @willdurand
